export const PAUSE_DEMO = 'demo/pause'
export const PLAY_DEMO = 'demo/play'
export const UPDATE_STEP = 'demo/updateStep'
export const UPDATE_NEXT_TICK = 'demo/updateNextTick'
export const TOGGLE_PLAY_PAUSE = 'demo/togglePlayPause'
