## Build Environment
FROM ambient/product:base_v1.0.0 as build
WORKDIR /app
# Copy project source files
COPY . /app
# Install missing deps
RUN npm install
# Create production builds
RUN REACT_APP_ENV=onprem npm run build

# Runtime Environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
