# Install Project Dependencies
# Use as base image for CI builds so they will
# be faster.
FROM node:13.12.0-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install
