const mockGroupedData = {
  '10.1.13.160': {
    ip: '10.1.13.160',
    name: '10.1.13.160 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.160',
        cameraMake: '',
        cameraModel: '',
        id: '141',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.160',
        cameraMake: '',
        cameraModel: '',
        id: '142',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.160',
        cameraMake: '',
        cameraModel: '',
        id: '143',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.160',
        cameraMake: '',
        cameraModel: '',
        id: '144',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.160',
        cameraMake: '',
        cameraModel: '',
        id: '145',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.160',
        cameraMake: '',
        cameraModel: '',
        id: '146',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.164': {
    ip: '10.1.13.164',
    name: '10.1.13.164 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.164',
        cameraMake: '',
        cameraModel: '',
        id: '164',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.164',
        cameraMake: '',
        cameraModel: '',
        id: '165',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.168': {
    ip: '10.1.13.168',
    name: '10.1.13.168 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.168',
        cameraMake: '',
        cameraModel: '',
        id: '168',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.168',
        cameraMake: '',
        cameraModel: '',
        id: '169',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.172': {
    ip: '10.1.13.172',
    name: '10.1.13.172 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.172',
        cameraMake: '',
        cameraModel: '',
        id: '172',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.172',
        cameraMake: '',
        cameraModel: '',
        id: '173',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.176': {
    ip: '10.1.13.176',
    name: '10.1.13.176 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.176',
        cameraMake: '',
        cameraModel: '',
        id: '176',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.176',
        cameraMake: '',
        cameraModel: '',
        id: '177',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.180': {
    ip: '10.1.13.180',
    name: '10.1.13.180 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.180',
        cameraMake: '',
        cameraModel: '',
        id: '180',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.180',
        cameraMake: '',
        cameraModel: '',
        id: '181',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.184': {
    ip: '10.1.13.184',
    name: '10.1.13.184 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.184',
        cameraMake: '',
        cameraModel: '',
        id: '184',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.184',
        cameraMake: '',
        cameraModel: '',
        id: '185',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.190': {
    ip: '10.1.13.190',
    name: '10.1.13.190 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.190',
        cameraMake: '',
        cameraModel: '',
        id: '190',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.190',
        cameraMake: '',
        cameraModel: '',
        id: '191',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.194': {
    ip: '10.1.13.194',
    name: '10.1.13.194 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.194',
        cameraMake: '',
        cameraModel: '',
        id: '194',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.194',
        cameraMake: '',
        cameraModel: '',
        id: '195',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
  '10.1.13.198': {
    ip: '10.1.13.198',
    name: '10.1.13.198 Cam',
    streamRequests: [
      {
        cameraIp: '10.1.13.198',
        cameraMake: '',
        cameraModel: '',
        id: '198',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
      {
        cameraIp: '10.1.13.198',
        cameraMake: '',
        cameraModel: '',
        id: '199',
        port: null,
        __typename: 'StreamDiscoveredType',
      },
    ],
  },
}
export default mockGroupedData
