export const SECURITY_PROFILE_SCHEDULE_FETCH_REQUESTED =
  'securityProfileSchedule/FETCH_REQUESTED'
export const SECURITY_PROFILE_SCHEDULE_FETCH_SUCCEEDED =
  'securityProfileSchedule/FETCH_SUCCEEDED'
export const SECURITY_PROFILE_SCHEDULE_FETCH_FAILED =
  'securityProfileSchedule/FETCH_FAILED'
export const SECURITY_PROFILE_SCHEDULE_UPDATE_REQUESTED =
  'securityProfileSchedule/UPDATE_REQUESTED'
export const SECURITY_PROFILE_SCHEDULE_UPDATE_SUCCEEDED =
  'securityProfileSchedule/UPDATE_SUCCEEDED'
export const SECURITY_PROFILE_SCHEDULE_UPDATE_FAILED =
  'securityProfileSchedule/UPDATE_FAILED'
