// SITES
export const FETCH_SITES_REQUESTED = 'cameras/FETCH_SITES_REQUESTED'
export const FETCH_SITES_SUCCEEDED = 'cameras/FETCH_SITES_SUCCEEDED'
export const FETCH_SITES_FAILED = 'cameras/FETCH_SITES_FAILED'

export const FETCH_REQUESTED = 'threatEscalation/FETCH_REQUESTED'
export const FETCH_SUCCEEDED = 'threatEscalation/FETCH_SUCCEEDED'
export const FETCH_FAILED = 'threatEscalation/FETCH_FAILED'

export const TOGGLE_SEV0_ESCALATION = 'threatEscalation/TOGGLE_SEV0_ESCALATION'

export const CREATE_ESCALATION_LEVEL_REQUESTED =
  'threatEscalation/CREATE_ESCALATION_LEVEL_REQUESTED'
export const CREATE_ESCALATION_LEVEL_SUCCEEDED =
  'threatEscalation/CREATE_ESCALATION_LEVEL_SUCCEEDED'
export const CREATE_ESCALATION_LEVEL_FAILED =
  'threatEscalation/CREATE_ESCALATION_LEVEL_FAILED'

export const DELETE_ESCALATION_LEVEL_REQUESTED =
  'threatEscalation/DELETE_ESCALATION_LEVEL_REQUESTED'
export const DELETE_ESCALATION_LEVEL_SUCCEEDED =
  'threatEscalation/DELETE_ESCALATION_LEVEL_SUCCEEDED'
export const DELETE_ESCALATION_LEVEL_FAILED =
  'threatEscalation/DELETE_ESCALATION_LEVEL_FAILED'

export const UPDATE_ESCALATION_LEVEL_REQUESTED =
  'threatEscalation/UPDATE_ESCALATION_LEVEL_REQUESTED'
export const UPDATE_ESCALATION_LEVEL_SUCCEEDED =
  'threatEscalation/UPDATE_ESCALATION_LEVEL_SUCCEEDED'
export const UPDATE_ESCALATION_LEVEL_FAILED =
  'threatEscalation/UPDATE_ESCALATION_LEVEL_FAILED'

export const CREATE_ESCALATION_CONTACT_REQUESTED =
  'threatEscalation/CREATE_ESCALATION_CONTACT_REQUESTED'
export const CREATE_ESCALATION_CONTACT_SUCCEEDED =
  'threatEscalation/CREATE_ESCALATION_CONTACT_SUCCEEDED'
export const CREATE_ESCALATION_CONTACT_FAILED =
  'threatEscalation/CREATE_ESCALATION_CONTACT_FAILED'

export const DELETE_ESCALATION_CONTACT_REQUESTED =
  'threatEscalation/DELETE_ESCALATION_CONTACT_REQUESTED'
export const DELETE_ESCALATION_CONTACT_SUCCEEDED =
  'threatEscalation/DELETE_ESCALATION_CONTACT_SUCCEEDED'
export const DELETE_ESCALATION_CONTACT_FAILED =
  'threatEscalation/DELETE_ESCALATION_CONTACT_FAILED'

export const UPDATE_ESCALATION_CONTACT_REQUESTED =
  'threatEscalation/UPDATE_ESCALATION_CONTACT_REQUESTED'
export const UPDATE_ESCALATION_CONTACT_SUCCEEDED =
  'threatEscalation/UPDATE_ESCALATION_CONTACT_SUCCEEDED'
export const UPDATE_ESCALATION_CONTACT_FAILED =
  'threatEscalation/UPDATE_ESCALATION_CONTACT_FAILED'

export const NOTIFICATION_METHODS_FETCH_REQUESTED =
  'threatEscalation/NOTIFICATION_METHODS_FETCH_REQUESTED'
export const NOTIFICATION_METHODS_FETCH_SUCCEEDED =
  'threatEscalation/NOTIFICATION_METHODS_FETCH_SUCCEEDED'
export const NOTIFICATION_METHODS_FETCH_FAILED =
  'threatEscalation/NOTIFICATION_METHODS_FETCH_FAILED'

export const PROFILES_FETCH_REQUESTED =
  'threatEscalation/PROFILES_FETCH_REQUESTED'
export const PROFILES_FETCH_SUCCEEDED =
  'threatEscalation/PROFILES_FETCH_SUCCEEDED'
export const PROFILES_FETCH_FAILED = 'threatEscalation/PROFILES_FETCH_FAILED'

export const REARRANGE_CONTACT_REQUESTED =
  'threatEscalation/REARRANGE_CONTACT_REQUESTED'
export const REARRANGE_CONTACT_SUCCEEDED =
  'threatEscalation/REARRANGE_CONTACT_SUCCEEDED'
export const REARRANGE_CONTACT_FAILED =
  'threatEscalation/REARRANGE_CONTACT_FAILED'

export const CREATE_ESCALATION_POLICY_FOR_SEV_REQUESTED =
  'threatEscalation/CREATE_ESCALATION_POLICY_FOR_SEV_REQUESTED'
export const CREATE_ESCALATION_POLICY_FOR_SEV_SUCCEEDED =
  'threatEscalation/CREATE_ESCALATION_POLICY_FOR_SEV_SUCCEEDED'
export const CREATE_ESCALATION_POLICY_FOR_SEV_FAILED =
  'threatEscalation/CREATE_ESCALATION_POLICY_FOR_SEV_FAILED'

export const UPDATE_ESCALATION_POLICY_FOR_SEV_REQUESTED =
  'threatEscalation/UPDATE_ESCALATION_POLICY_FOR_SEV_REQUESTED'
export const UPDATE_ESCALATION_POLICY_FOR_SEV_SUCCEEDED =
  'threatEscalation/UPDATE_ESCALATION_POLICY_FOR_SEV_SUCCEEDED'
export const UPDATE_ESCALATION_POLICY_FOR_SEV_FAILED =
  'threatEscalation/UPDATE_ESCALATION_POLICY_FOR_SEV_FAILED'

export const GET_ESCALATION_POLICIES_REQUESTED =
  'threatEscalation/GET_ESCALATION_POLICIES_REQUESTED'
export const GET_ESCALATION_POLICIES_SUCCEEDED =
  'threatEscalation/GET_ESCALATION_POLICIES_SUCCEEDED'
export const GET_ESCALATION_POLICIES_FAILED =
  'threatEscalation/GET_ESCALATION_POLICIES_FAILED'

export const DELETE_ESCALATION_POLICY_REQUESTED =
  'threatEscalation/DELETE_ESCALATION_POLICY_REQUESTED'
export const DELETE_ESCALATION_POLICY_SUCCEEDED =
  'threatEscalation/DELETE_ESCALATION_POLICY_SUCCEEDED'
export const DELETE_ESCALATION_POLICY_FAILED =
  'threatEscalation/DELETE_ESCALATION_POLICY_FAILED'

export const GET_ESCALATION_POLICY_REQUESTED =
  'threatEscalation/GET_ESCALATION_POLICY_REQUESTED'
export const GET_ESCALATION_POLICY_SUCCEEDED =
  'threatEscalation/GET_ESCALATION_POLICY_SUCCEEDED'
export const GET_ESCALATION_POLICY_FAILED =
  'threatEscalation/GET_ESCALATION_POLICY_FAILED'
