const HEADROOM_HEIGHT = 40 // extra blank space above the timeline
const TIMELINE_HEIGHT = 40
const TOTAL_HEIGHT = HEADROOM_HEIGHT + TIMELINE_HEIGHT

// Clickable Timeline
const THIN_TIMELINE_HEIGHT = 5
const EXPANDED_TIMELINE_HEIGHT = 7
const TIME_MARKER_HEIGHT = 15
const CLICKABLE_TIMELINE_HEIGHT = TIME_MARKER_HEIGHT + THIN_TIMELINE_HEIGHT
const TIMELINE_CLICKABLE_HEADROOM = 20

// Hoverline
const HOVERLINE_HEIGHT_ABOVE = 10
const HOVERLINE_HEIGHT = HOVERLINE_HEIGHT_ABOVE + THIN_TIMELINE_HEIGHT
const HOVERLINE_WIDTH = 2

// Draggable Timeline
const DRAG_HEIGHT = 40
const DRAG_EXPAND_HEIGHT = 40

// Edges
const EDGE_HEIGHT = 80
const EDGE_WIDTH = 30
const EDGE_EXPAND_WIDTH = 30

// Hoverable Timeline

// Playhead
const PLAYHEAD_BALL_RADIUS = 6
const PLAYHEAD_WIDTH = 2
const PLAYHEAD_BELOW_HEIGHT = 7

export {
  CLICKABLE_TIMELINE_HEIGHT,
  DRAG_HEIGHT,
  DRAG_EXPAND_HEIGHT,
  EDGE_HEIGHT,
  EDGE_WIDTH,
  EDGE_EXPAND_WIDTH,
  EXPANDED_TIMELINE_HEIGHT,
  HEADROOM_HEIGHT,
  HOVERLINE_HEIGHT,
  HOVERLINE_WIDTH,
  PLAYHEAD_BALL_RADIUS,
  PLAYHEAD_BELOW_HEIGHT,
  PLAYHEAD_WIDTH,
  TIMELINE_HEIGHT,
  TOTAL_HEIGHT,
  THIN_TIMELINE_HEIGHT,
  TIMELINE_CLICKABLE_HEADROOM,
}
