const InventoryStatusEnum = Object.freeze({
  NEW: 'NEW',
  PENDING_BUILD: 'PENDING_BUILD',
  PENDING_INSTALLATION: 'PENDING_INSTALLATION',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  READY_TO_SHIP: 'READY_TO_SHIP',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  ONLINE: 'ONLINE',
  PROVISIONED: 'PROVISIONED',
  BLOCKED: 'BLOCKED',
})

export default InventoryStatusEnum
