// Node Request Types
const NodeRequestTypeEnum = {
  CAPTURE_FRAME: 'CAPTURE_FRAME',
  DELETE_LOG_BUNDLE: 'DELETE_LOG_BUNDLE',
  DISCOVERY: 'DISCOVERY',
  EXTRACT_CROP: 'EXTRACT_CROP',
  LDAP: 'LDAP',
  LOG_BUNDLE: 'LOG_BUNDLE',
  RESTART: 'RESTART',
  SYNC_IDENTITY_SOURCE: 'SYNC_IDENTITY_SOURCE',
  UPGRADE: 'UPGRADE',
  VERSION: 'VERSION',

}

export default NodeRequestTypeEnum
