const StreamStateEnum = Object.freeze({
  READY: 'READY',
  LOADING: 'LOADING',
  ASSIGNED: 'ASSIGNED',
  LOADED: 'LOADED',
  STOPPED: 'STOPPED',
  PLAYING: 'PLAYING',
  HANGING_UP: 'HANGING_UP',
  DISCONNECTED: 'DISCONNECTED',
  MAX_CLIENTS: 'MAX_CLIENTS',
})

export default StreamStateEnum
