const WebSocketActionTypeEnum = Object.freeze({
  ACKNOWLEDGE_ALERT: 'ACKNOWLEDGE_ALERT',
  ADD_ALERT_INSTANCE: 'ADD_ALERT_INSTANCE',
  ADD_COMMENT: 'ADD_COMMENT',
  ALERT_ACKED: 'alert_acked',
  CLOSE_CASE: 'CLOSE_CASE',
  MERGE_CASE: 'MERGE_CASE',
  OPEN_CASE: 'OPEN_CASE',
  PING: 'PING',
  REMOVE_ALERT_INSTANCE: 'REMOVE_ALERT_INSTANCE',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  REOPEN_CASE: 'REOPEN_CASE',
  REQUEST_DISPATCH: 'REQUEST_DISPATCH',
})

export default WebSocketActionTypeEnum
