// SITES
export const FETCH_SITES_REQUESTED = 'cameras/FETCH_SITES_REQUESTED'
export const FETCH_SITES_SUCCEEDED = 'cameras/FETCH_SITES_SUCCEEDED'
export const FETCH_SITES_FAILED = 'cameras/FETCH_SITES_FAILED'
export const UPDATE_STREAM_SITE_REQUESTED =
  'cameras/UPDATE_STREAM_SITE_REQUESTED'
export const UPDATE_STREAM_SITE_SUCCEEDED =
  'cameras/UPDATE_STREAM_SITE_SUCCEEDED'
export const UPDATE_STREAM_SITE_FAILED = 'cameras/UPDATE_STREAM_SITE_FAILED'

// STREAMS
export const FIND_STREAMS_REQUESTED = 'cameras/FIND_STREAMS_REQUESTED'
export const FIND_STREAMS_SUCCEEDED = 'cameras/FIND_STREAMS_SUCCEEDED'
export const FIND_STREAMS_FAILED = 'cameras/FIND_STREAMS_FAILED'
export const SET_SORT_OPTIONS = 'cameras/SET_SORT_OPTIONS'

// STREAM HEALTH
export const SET_STREAM_HEALTH = 'cameras/SET_STREAM_HEALTH'
export const SET_STREAM_SEARCH_TERM = 'cameras/SET_STREAM_SEARCH_TERM'
export const SET_STREAM_HEALTH_IS_TABLE_UPDATED =
  'cameras/SET_STREAM_HEALTH_IS_TABLE_UPDATED'
export const SET_STREAM_HEALTH_LOADING = 'cameras/SET_STREAM_HEALTH_LOADING'

// STREAM IDS FOR SITE
export const GET_ALL_STREAM_IDS_FOR_SITE_REQUESTED =
  'cameras/GET_ALL_STREAM_IDS_FOR_SITE_REQUESTED'
export const GET_ALL_STREAM_IDS_FOR_SITE_SUCCEEDED =
  'cameras/GET_ALL_STREAM_IDS_FOR_SITE_SUCCEEDED'
export const GET_ALL_STREAM_IDS_FOR_SITE_FAILED =
  'cameras/GET_ALL_STREAM_IDS_FOR_SITE_FAILED'

export const SET_EDITABLE_TABLE = 'cameras/SET_EDITABLE_TABLE'
