const SECONDS_IN_HOUR = 3600
const MINUTES_IN_HOUR = 60
const SECONDS_IN_MINUTE = 60
const HOURS_IN_DAY = 24
const MIN_ENTITY_DOC_COUNT = 1
const SECONDS_IN_DAY = 86400
const MINUTES_IN_DAY = 1440
const WIDTH_OF_ENTITY_MARKER_MIN = 10
const WIDTH_OF_ENTITY_MARKER_HRS = 2
const PLAYPOINTER_POSITION_OFFSET = 200
const VIEWWINDOW_OFFSET_HRS = 60 * 60 * 5
const VIEWWINDOW_OFFSET_MIN = 60 * 60 * 4
const PROGRESS_BAR_WIDTH_INCREMENT = 100 / (24 * 3600)
const PLAY_POINTER_POSITION_INCREMENT_MINS = 1
const PLAY_POINTER_POSITION_INCREMENT_HRS = 1 / 60

export {
  SECONDS_IN_HOUR,
  MINUTES_IN_HOUR,
  SECONDS_IN_MINUTE,
  HOURS_IN_DAY,
  MIN_ENTITY_DOC_COUNT,
  SECONDS_IN_DAY,
  MINUTES_IN_DAY,
  WIDTH_OF_ENTITY_MARKER_HRS,
  WIDTH_OF_ENTITY_MARKER_MIN,
  PLAYPOINTER_POSITION_OFFSET,
  VIEWWINDOW_OFFSET_HRS,
  VIEWWINDOW_OFFSET_MIN,
  PROGRESS_BAR_WIDTH_INCREMENT,
  PLAY_POINTER_POSITION_INCREMENT_HRS,
  PLAY_POINTER_POSITION_INCREMENT_MINS,
}
