export const FETCH_ALL_BY_ACCOUNT_REQUESTED =
  'sites/FETCH_ALL_BY_ACCOUNT_REQUESTED'
export const FETCH_ALL_BY_ACCOUNT_SUCCEEDED =
  'sites/FETCH_ALL_BY_ACCOUNT_SUCCEEDED'
export const FETCH_ALL_BY_ACCOUNT_FAILED = 'sites/FETCH_ALL_BY_ACCOUNT_FAILED'

export const FETCH_SITE_UP_TIME_REQUESTED = 'sites/FETCH_SITE_UP_TIME_REQUESTED'
export const FETCH_SITE_UP_TIME_SUCCEEDED = 'sites/FETCH_SITE_UP_TIME_SUCCEEDED'
export const FETCH_SITE_UP_TIME_FAILED = 'sites/FETCH_SITE_UP_TIME_FAILED'

export const FETCH_NODE_STATISTICS_REQUESTED =
  'sites/FETCH_NODE_STATISTICS_REQUESTED'
export const FETCH_NODE_STATISTICS_SUCCEEDED =
  'sites/FETCH_NODE_STATISTICS_SUCCEEDED'
export const FETCH_NODE_STATISTICS_FAILED = 'sites/FETCH_NODE_STATISTICS_FAILED'

export const FETCH_TIMEZONES_REQUESTED = 'sites/FETCH_TIMEZONES_REQUESTED'
export const FETCH_TIMEZONES_SUCCEEDED = 'sites/FETCH_TIMEZONES_SUCCEEDED'
export const FETCH_TIMEZONES_FAILED = 'sites/FETCH_TIMEZONES_FAILED'

export const SET_SITE_UPDATING = 'sites/SET_SITE_UPDATING'
export const UPDATE_SITE_INFO_REQUESTED = 'sites/UPDATE_SITE_INFO_REQUESTED'
export const UPDATE_SITE_INFO_FAILED = 'sites/UPDATE_SITE_INFO_FAILED'
export const UPDATE_SITE_INFO_SUCCEEDED = 'sites/UPDATE_SITE_INFO_SUCCEEDED'
