export const ESCALATION_CONTACT_FETCH_REQUESTED =
  'mobileEscalation/ESCALATION_CONTACT_FETCH_REQUESTED'
export const ESCALATION_CONTACT_FETCH_SUCCEEDED =
  'mobileEscalation/ESCALATION_CONTACT_FETCH_SUCCEEDED'
export const ESCALATION_CONTACT_FETCH_FAILED =
  'mobileEscalation/ESCALATION_CONTACT_FETCH_FAILED'

export const SNOOZE_ESCALATION_METHOD_REQUESTED =
  'mobileEscalation/SNOOZE_ESCALATION_METHOD_REQUESTED'
export const SNOOZE_ESCALATION_METHOD_SUCCEEDED =
  'mobileEscalation/SNOOZE_ESCALATION_METHOD_SUCCEEDED'
export const SNOOZE_ESCALATION_METHOD_FAILED =
  'mobileEscalation/SNOOZE_ESCALATION_METHOD_FAILED'

export const UNSNOOZE_ESCALATION_METHOD_REQUESTED =
  'mobileEscalation/UNSNOOZE_ESCALATION_METHOD_REQUESTED'
export const UNSNOOZE_ESCALATION_METHOD_SUCCEEDED =
  'mobileEscalation/UNSNOOZE_ESCALATION_METHOD_SUCCEEDED'
export const UNSNOOZE_ESCALATION_METHOD_FAILED =
  'mobileEscalation/UNSNOOZE_ESCALATION_METHOD_FAILED'
