// const prefix = 'contextGraph'

export const FETCH_ALERTS_REQUEST = 'contextGraph/FETCH_ALERTS_REQUEST'
export const FETCH_ALERTS_SUCCEEDED = 'contextGraph/FETCH_ALERTS_SUCCEEDED'
export const FETCH_ALERTS_FAILED = 'contextGraph/FETCH_ALERTS_FAILED'

export const FETCH_DEFAULT_ALERTS_REQUEST =
  'contextGraph/FETCH_DEFAULT_ALERTS_REQUEST'
export const FETCH_DEFAULT_ALERTS_SUCCEEDED =
  'contextGraph/FETCH_DEFAULT_ALERTS_SUCCEEDED'
export const FETCH_DEFAULT_ALERTS_FAILED =
  'contextGraph/FETCH_DEFAULT_ALERTS_FAILED'

export const FILTER_ACTIVE = 'contextGraph/FILTER_ACTIVE'
export const FILTER_SEVERITY = 'contextGraph/FILTER_SEVERITY'

export const THREAT_SIGNATURE_AUTOCOMPLETE_REQUEST =
  'contextGraph/THREAT_SIGNATURE_AUTOCOMPLETE_REQUEST'
export const THREAT_SIGNATURE_AUTOCOMPLETE_SUCCEEDED =
  'contextGraph/THREAT_SIGNATURE_AUTOCOMPLETE_SUCCEEDED'
export const THREAT_SIGNATURE_AUTOCOMPLETE_FAILED =
  'contextGraph/THREAT_SIGNATURE_AUTOCOMPLETE_FAILED'

export const CREATE_ALERT_REQUEST = 'contextGraph/CREATE_ALERT_REQUEST'
export const CREATE_ALERT_SUCCEEDED = 'contextGraph/CREATE_ALERT_SUCCEEDED'
export const CREATE_ALERT_FAILED = 'contextGraph/CREATE_ALERT_FAILED'

export const CREATE_DEFAULT_ALERT_REQUEST =
  'contextGraph/CREATE_DEFAULT_ALERT_REQUEST'
export const CREATE_DEFAULT_ALERT_SUCCEEDED =
  'contextGraph/CREATE_DEFAULT_ALERT_SUCCEEDED'

export const UPDATE_ALERT_SNOOZE_REQUEST =
  'contextGraph/UPDATE_ALERT_SNOOZE_REQUEST'
export const UPDATE_ALERT_SNOOZE_SUCCEEDED =
  'contextGraph/UPDATE_ALERT_SNOOZE_SUCCEEDED'

export const UPDATE_ALERT_STREAMS_REQUEST =
  'contextGraph/UPDATE_ALERT_STREAMS_REQUEST'
export const UPDATE_ALERT_STREAMS_SUCCEEDED =
  'contextGraph/UPDATE_ALERT_STREAMS_SUCCEEDED'

export const DELETE_ALERT_REQUEST = 'contextGraph/DELETE_ALERT_REQUEST'
export const DELETE_ALERT_SUCCEEDED = 'contextGraph/DELETE_ALERT_SUCCEEDED'
export const DELETE_ALERT_FAILED = 'contextGraph/DELETE_ALERT_FAILED'

export const TOGGLE_ALERT_STATUS_REQUEST =
  'contextGraph/TOGGLE_ALERT_STATUS_REQUEST'
export const TOGGLE_ALERT_STATUS_SUCCEEDED =
  'contextGraph/TOGGLE_ALERT_STATUS_SUCCEEDED'
export const TOGGLE_ALERT_STATUS_FAILED =
  'contextGraph/TOGGLE_ALERT_STATUS_FAILED'

export const SET_SEARCH = 'contextGraph/SET_SEARCH'
export const SET_HOVERED = 'contextGraph/SET_HOVERED'
export const TOGGLE_ACTIVE = 'contextGraph/TOGGLE_ACTIVE'
export const SET_DETAILED = 'contextGraph/SET_DETAILED'
// Create alert form
export const SET_CREATE_ALERT_OPEN = 'contextGraph/SET_CREATE_ALERT_OPEN'
export const SET_CREATE_DEFAULT_ALERT_OPEN =
  'contextGraph/SET_CREATE_DEFAULT_ALERT_OPEN'

export const SET_THREAT_SIGNATURE_AUTOCOMPLETE_FLAT =
  'contextGraph/SET_THREAT_SIGNATURE_AUTOCOMPLETE_FLAT'

export const TOGGLE_EDGES = 'contextGraph/TOGGLE_EDGES'

// SITES
export const FETCH_SITES_REQUESTED = 'contextGraph/FETCH_SITES_REQUESTED'
export const FETCH_SITES_SUCCEEDED = 'contextGraph/FETCH_SITES_SUCCEEDED'
export const FETCH_SITES_FAILED = 'contextGraph/FETCH_SITES_FAILED'

// STREAMS

export const FETCH_STREAMS_REQUESTED = 'contextGraph/FETCH_STREAMS_REQUESTED'
export const FETCH_STREAMS_SUCCEEDED = 'contextGraph/FETCH_STREAMS_SUCCEEDED'
export const FETCH_STREAMS_FAILED = 'contextGraph/FETCH_STREAMS_FAILED'

// REGIONS

export const FETCH_REGIONS_REQUESTED = 'contextGraph/FETCH_REGIONS_REQUESTED'
export const FETCH_REGIONS_SUCCEEDED = 'contextGraph/FETCH_REGIONS_SUCCEEDED'
export const FETCH_REGIONS_FAILED = 'contextGraph/FETCH_REGIONS_FAILED'

export const SET_HOVERED_REGION = 'contextGraph/SET_HOVERED_REGION'
export const TOGGLE_ACTIVE_REGION = 'contextGraph/TOGGLE_ACTIVE_REGION'

// SP

export const FETCH_REQUESTED = 'contextGraph/FETCH_REQUESTED'
export const FETCH_SUCCEEDED = 'contextGraph/FETCH_SUCCEEDED'
export const FETCH_FAILED = 'contextGraph/FETCH_FAILED'

export const FETCH_DEFAULTS_REQUESTED = 'contextGraph/FETCH_DEFAULTS_REQUESTED'
export const FETCH_DEFAULTS_SUCCEEDED = 'contextGraph/FETCH_DEFAULTS_SUCCEEDED'
export const FETCH_DEFAULTS_FAILED = 'contextGraph/FETCH_DEFAULTS_FAILED'

export const CREATE_REQUESTED = 'contextGraph/CREATE_REQUESTED'
export const CREATE_SUCCEEDED = 'contextGraph/CREATE_SUCCEEDED'
export const CREATE_FAILED = 'contextGraph/CREATE_FAILED'

export const REMOVE_REQUESTED = 'contextGraph/REMOVE_REQUESTED'
export const REMOVE_SUCCEEDED = 'contextGraph/REMOVE_SUCCEEDED'
export const REMOVE_FAILED = 'contextGraph/REMOVE_FAILED'

export const UPDATE_REQUESTED = 'contextGraph/UPDATE_REQUESTED'
export const UPDATE_SUCCEEDED = 'contextGraph/UPDATE_SUCCEEDED'
export const UPDATE_FAILED = 'contextGraph/UPDATE_FAILED'

export const SAVE_THREAT_MODEL_REQUESTED =
  'contextGraph/SAVE_THREAT_MODEL_REQUESTED'
export const SAVE_THREAT_MODEL_SUCCEEDED =
  'contextGraph/SAVE_THREAT_MODEL_SUCCEEDED'
export const SAVE_THREAT_MODEL_FAILED = 'contextGraph/SAVE_THREAT_MODEL_FAILED'

export const DELETE_ALERT = 'contextGraph/DELETE_ALERT'

export const SELECT_SECURITY_PROFILE = 'contextGraph/SELECT_SECURITY_PROFILE'

export const SET_PREVIEW = 'contextGraph/SET_PREVIEW'
export const UN_SET_PREVIEW = 'contextGraph/UN_SET_PREVIEW'
