export const CREATE_ACCESS_ALARM_REQUESTED =
  'access/CREATE_ACCESS_ALARM_REQUESTED'
export const CREATE_ACCESS_ALARM_SUCCEEDED =
  'access/CREATE_ACCESS_ALARM_SUCCEEDED'
export const CREATE_ACCESS_ALARM_FAILED = 'access/CREATE_ACCESS_ALARM_FAILED'
