const VMS = 'vms'

export const SET_HOVER_ON_VIDEO = `${VMS}/SET_HOVER_ON_VIDEO`
export const SET_HOVER_OFF_VIDEO = `${VMS}/SET_HOVER_OFF_VIDEO`
export const SET_TIMELINE_SETTING_POSITION = `${VMS}/SET_TIMELINE_SETTING_POSITION`
export const TOGGLE_FULLSCREEN_MODE = `${VMS}/TOGGLE_FULLSCREEN_MODE`
export const TOGGLE_DARK_MODE = `${VMS}/TOGGLE_DARK_MODE`
export const TOGGLE_SHOW_ALERTS = `${VMS}/TOGGLE_SHOW_ALERTS`
