import React from 'react'
import { storiesOf, addDecorator } from '@storybook/react' // eslint-disable-line
import { withKnobs, text, boolean, number } from '@storybook/addon-knobs' // eslint-disable-line

import Icon from './index'
import { iconCode } from './addons/notes'

addDecorator(withKnobs)

storiesOf('Icon', module).add(
  'Icons',
  () => {
    const colorKnob = text('color', 'black')
    const sizeKnob = number('size', 24)
    const animateKnob = boolean('animate', false)
    return (
      <div style={{ display: 'flex', flexDirection: 'row' }}>
        <Icon
          icon='activity'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='alertCircle'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='arrowUp'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='arrowDown'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='back'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='back'
          fillOnlyIcon='1'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='back'
          fillOnlyIcon='5'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='back'
          fillOnlyIcon='back10'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='bell'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='bookmark'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='box'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='camera'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='checkCircle'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='close'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='eye'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='grid'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='help'
          fillOnlyIcon='helpO'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='forward'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='forward'
          fillOnlyIcon='1'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='forward'
          fillOnlyIcon='5'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='forward'
          fillOnlyIcon='forward10'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='search'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='list'
          fill={colorKnob}
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='moon'
          fill={colorKnob}
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='person'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='play'
          fill={colorKnob}
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='phone'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='sites'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='sun'
          fill={colorKnob}
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='trash'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
        <Icon
          icon='maximize'
          color={colorKnob}
          size={sizeKnob}
          animate={animateKnob}
        />
      </div>
    )
  },
  {
    notes: {
      Code: iconCode,
    },
  },
)
