// entity action types
export const ENTITY_FETCH_REQUESTED = 'forensics/ENTITY_FETCH_REQUESTED'
export const ENTITY_FETCH_FAILED = 'forensics/ENTITY_FETCH_FAILED'
export const ENTITY_FETCH_SUCCEEDED = 'forensics/ENTITY_FETCH_SUCCEEDED'
export const RESET_SEARCH = 'forensics/RESET_SEARCH'
export const SET_RANGE_PRESET_INDEX = 'forensics/SET_RANGE_PRESET_INDEX'
export const SET_SEARCH_QUERY = 'forensics/SET_SEARCH_QUERY'
export const SET_SEARCH_TS_RANGE = 'forensics/SET_SEARCH_TS_RANGE'
export const SET_SELECTION_TS_RANGE = 'forensics/SET_SELECTION_TS_RANGE'
export const TOGGLE_SHOULD_GENERATE_NEW_SEARCH =
  'forensics/TOGGLE_SHOULD_GENERATE_NEW_SEARCH'

// region action types
export const REGIONS_FETCH_REQUESTED = 'forensics/REGIONS_FETCH_REQUESTED'
export const REGIONS_FETCH_SUCCEEDED = 'forensics/REGIONS_FETCH_SUCCEEDED'
export const REGIONS_FETCH_FAILED = 'forensics/REGIONS_FETCH_FAILED'
export const SET_HOVERED_REGION = 'forensics/SET_HOVERED_REGION'
export const TOGGLE_ACTIVE_REGION = 'forensics/TOGGLE_ACTIVE_REGION'
export const SET_ACTIVE_REGIONS = 'forensics/SET_ACTIVE_REGIONS'
export const SELECT_REGION = 'forensics/SELECT_REGION'

// site action types
export const SITES_FETCH_REQUESTED = 'forensics/SITES_FETCH_REQUESTED'
export const SITES_FETCH_SUCCEEDED = 'forensics/SITES_FETCH_SUCCEEDED'
export const SITES_FETCH_FAILED = 'forensics/SITES_FETCH_FAILED'
export const SET_SELECTED_SITE = 'forensics/SET_SELECTED_SITE'
export const SET_SELECTED_TIMEZONE = 'forensics/SET_SELECTED_TIMEZONE'

// streams
export const STREAMS_FETCH_REQUESTED = 'forensics/STREAMS_FETCH_REQUESTED'
export const STREAMS_FETCH_SUCCEEDED = 'forensics/STREAMS_FETCH_SUCCEEDED'
export const STREAMS_FETCH_FAILED = 'forensics/STREAMS_FETCH_FAILED'
export const TOGGLE_ACTIVE_STREAM = 'forensics/TOGGLE_ACTIVE_STREAM'
export const SET_ACTIVE_STREAM = 'forensics/SET_ACTIVE_STREAM'

// pagination
export const SET_SELECTED_PAGE = 'forensics/SET_SELECTED_PAGE'

// region stats action types
export const REGION_STATS_FETCH_REQUESTED =
  'forensics/REGION_STATS_FETCH_REQUESTED'
export const REGION_STATS_FETCH_SUCCEEDED =
  'forensics/REGION_STATS_FETCH_SUCCEEDED'
export const REGION_STATS_FETCH_FAILED = 'forensics/REGION_STATS_FETCH_FAILED'

// snapshots
export const SNAPSHOTS_FETCH_REQUESTED = 'forensics/SNAPSHOTS_FETCH_REQUESTED'
export const SNAPSHOTS_FETCH_SUCCEEDED = 'SNAPSHOTS_FETCH_SUCCEEDED'
export const SNAPSHOTS_FETCH_FAILED = 'SNAPSHOTS_FETCH_FAILED'

export const ADD_REGION_NODES = 'forensics/ADD_REGION_NODES'
export const UPDATE_STREAM_NODE_DATA = 'forensics/UPDATE_STREAM_NODE_DATA'
export const UPDATE_STREAM_NODES = 'forensics/UPDATE_STREAM_NODES'
export const UPDATE_INCIDENT_NODES = 'forensics/UPDATE_INCIDENT_NODES'

export const ADD_VIABLE_REGIONS_COUNT = 'forensics/ADD_VIABLE_REGIONS_COUNT'

export const ACTIVATE_ALL_REGION_STREAMS =
  'forensics/ACTIVATE_ALL_REGION_STREAMS'
export const DEACTIVATE_ALL_REGION_STREAMS =
  'forensics/DEACTIVATE_ALL_REGION_STREAMS'

export const CLEAR_SELECTED_REGION = 'forensics/CLEAR_SELECTED_REGION'

export const UPDATE_GRAPH_PAGE = 'forensics/UPDATE_GRAPH_PAGE'

export const SUGGESTIONS_FETCH_REQUESTED =
  'forensics/SUGGESTIONS_FETCH_REQUESTED'
export const SUGGESTIONS_FETCH_SUCCEEDED =
  'forensics/SUGGESTIONS_FETCH_SUCCEEDED'
export const SUGGESTIONS_FETCH_FAILED = 'forensics/SUGGESTIONS_FETCH_FAILED'

export const THREAT_SIGNATURE_FETCH_REQUESTED =
  'forensics/THREAT_SIGNATURE_FETCH_REQUESTED'
export const THREAT_SIGNATURE_REGION_STATS_FETCH_REQUESTED =
  'forensics/THREAT_SIGNATURE_REGION_STATS_FETCH_REQUESTED'
export const THREAT_SIGNATURE_STREAM_STATS_FETCH_REQUESTED =
  'forensics/THREAT_SIGNATURE_STREAM_STATS_FETCH_REQUESTED'

export const SET_SELECTED_SUGGESTION = 'forensics/SET_SELECTED_SUGGESTION'

// STREAM SEARCH
export const SET_STREAM_QUERY = 'forensics/SET_STREAM_QUERY'

export const SET_HOVERED_STREAM = 'forensics/SET_HOVERED_STREAM'

export const SET_IS_REID_SEARCH_VISIBLE = 'forensics/SET_IS_REID_SEARCH_VISIBLE'
export const ADD_HISTORY_ITEM = 'forensics/ADD_HISTORY_ITEM'

export const SET_VEHICLE_FILTER = 'forensics/SET_VEHICLE_FILTER'
