export const CHANGE_DATE_FILTER = 'reports/CHANGE_DATE_FILTER'
export const CHANGE_ALERT_EVENTS = 'reports/CHANGE_ALERT_EVENTS'
export const DISPLAY_ALERT_EVENTS = 'reports/DISPLAY_ALERT_EVENTS'

export const FETCH_SITES_REQUESTED = 'reports/FETCH_SITES_REQUESTED'
export const FETCH_SITES_SUCCEEDED = 'reports/FETCH_SITES_SUCCEEDED'
export const FETCH_SITES_FAILED = 'reports/FETCH_SITES_FAILED'
