const mockData = {
  activityReport: {
    numAlertEvents: 32,
    numAckedAlertEvents: 28,
    numOutstandingAlertEvents: 4,
    numDispatchedAlertEvents: 10,
  },
  acknowledgementLatencyDistribution: [
    { name: '<1', value: 17, alertEvents: [], total: 28 },
    { name: '1-2', value: 3, alertEvents: [], total: 28 },
    { name: '2-5', value: 3, alertEvents: [], total: 28 },
    { name: '5-10', value: 2, alertEvents: [], total: 28 },
    { name: '10-60', value: 2, alertEvents: [], total: 28 },
    { name: '>60', value: 1, alertEvents: [], total: 28 },
  ],
  timeToActionLatencyDistribution: [
    { name: '<1', value: 18, alertEvents: [], total: 28 },
    { name: '1-2', value: 5, alertEvents: [], total: 28 },
    { name: '2-5', value: 3, alertEvents: [], total: 28 },
    { name: '5-10', value: 1, alertEvents: [], total: 28 },
    { name: '10-60', value: 1, alertEvents: [], total: 28 },
    { name: '>60', value: 0, alertEvents: [], total: 28 },
  ],
  dispatchLatencyDistribution: [
    { name: '<2', value: 2, alertEvents: [], total: 10 },
    { name: '2-5', value: 3, alertEvents: [], total: 10 },
    { name: '5-10', value: 3, alertEvents: [], total: 10 },
    { name: '10-15', value: 1, alertEvents: [], total: 10 },
    { name: '>15', value: 1, alertEvents: [], total: 10 },
  ],
  alertDistribution: [
    { name: 'Verified Door Propped Open', value: 2 },
    { name: 'Verified Tailgate', value: 4 },
    { name: 'Crowding', value: 4 },
    { name: 'Attempted Unusual Entry', value: 3 },
    { name: 'Person Falling Down', value: 1 },
    { name: 'Person Loitering at Entrance After Hours', value: 3 },
    { name: 'Person Carrying Laptop from Secure Room', value: 2 },
    { name: 'Multiple people exiting vehicle', value: 2 },
  ],
  activityDistribution: [
    { name: 'Door Held Open (DHO)', value: 96 },
    { name: 'Door Forced Open (DFO)', value: 72 },
    { name: 'Access Denied', value: 12 },
    { name: 'Tailgating', value: 62 },
    { name: 'Loitering in Parking Lot', value: 12 },
    { name: 'Front Desk Unattended', value: 24 },
  ],
  userActivityReports: [
    {
      name: 'Vikesh Khanna',
      dispatchesSeen: 4,
      dispatchesReceived: 5,
      dispatchesResolved: 3,
      dispatchesDenied: 1,
      ackedAlertEvents: 12,
    },
    {
      name: 'Carly Stoughton',
      dispatchesSeen: 5,
      dispatchesReceived: 5,
      dispatchesResolved: 2,
      dispatchesDenied: 0,
      ackedAlertEvents: 8,
    },
    {
      name: 'Shikhar Shrestha',
      dispatchesSeen: 10,
      dispatchesReceived: 10,
      dispatchesResolved: 6,
      dispatchesDenied: 2,
      ackedAlertEvents: 8,
    },
    {
      name: 'James Connor',
      dispatchesSeen: 4,
      dispatchesReceived: 8,
      dispatchesResolved: 1,
      dispatchesDenied: 2,
      ackedAlertEvents: 4,
    },
  ],
}

export default mockData
